version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'example'
      POSTGRES_DB: 'transcendence'
      POSTGRES_HOST: 'localhost'
    expose:
      - "5432"
    ports:
      - 5432:5432
    networks:
      - transcendence

  nestjs:
    build:
      context: "./src/back"
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      - .env
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'example'
      POSTGRES_DB: 'transcendence'
      POSTGRES_HOST: 'db'
    networks:
      - transcendence
    dns_search:
      - transcendence

  react:
    build:
      context: "./src/front"
      dockerfile: Dockerfile
    ports:
      - "3133:3133"
    depends_on:
      - db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'example'
      POSTGRES_DB: 'transcendence'
      POSTGRES_HOST: 'db'
    networks:
      - transcendence

volumes:
  db:

networks:
  transcendence:
    driver: bridge
